"""typechange

Revision ID: 000074b888a8
Revises: ff8959d379ae
Create Date: 2025-05-08 15:20:14.153531

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '000074b888a8'
down_revision = 'ff8959d379ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###