"""change time and hits

Revision ID: 4b244eba70dc
Revises: b26f22ff3db6
Create Date: 2025-05-09 15:24:23.990032

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b244eba70dc'
down_revision = 'b26f22ff3db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alarm', 'receive_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=True)
    op.add_column('newspaper', sa.Column('hits', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newspaper', 'hits')
    op.alter_column('alarm', 'receive_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
