"""deletecascade

Revision ID: 51e3e0e713c1
Revises: 3e02c0982027
Create Date: 2025-05-12 11:27:17.452332

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '51e3e0e713c1'
down_revision = '3e02c0982027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alarm', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('alarm_user_id_fkey', 'alarm', type_='foreignkey')
    op.create_foreign_key(None, 'alarm', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('newspapercategory_newspaper_id_fkey', 'newspapercategory', type_='foreignkey')
    op.create_foreign_key(None, 'newspapercategory', 'newspaper', ['newspaper_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('usercategory_user_id_fkey', 'usercategory', type_='foreignkey')
    op.create_foreign_key(None, 'usercategory', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('usernewspaperpreference_newspaper_id_fkey', 'usernewspaperpreference', type_='foreignkey')
    op.drop_constraint('usernewspaperpreference_user_id_fkey', 'usernewspaperpreference', type_='foreignkey')
    op.create_foreign_key(None, 'usernewspaperpreference', 'newspaper', ['newspaper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'usernewspaperpreference', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('usernewspapersave_user_id_fkey', 'usernewspapersave', type_='foreignkey')
    op.create_foreign_key(None, 'usernewspapersave', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usernewspapersave', type_='foreignkey')
    op.create_foreign_key('usernewspapersave_user_id_fkey', 'usernewspapersave', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'usernewspaperpreference', type_='foreignkey')
    op.drop_constraint(None, 'usernewspaperpreference', type_='foreignkey')
    op.create_foreign_key('usernewspaperpreference_user_id_fkey', 'usernewspaperpreference', 'user', ['user_id'], ['id'])
    op.create_foreign_key('usernewspaperpreference_newspaper_id_fkey', 'usernewspaperpreference', 'newspaper', ['newspaper_id'], ['id'])
    op.drop_constraint(None, 'usercategory', type_='foreignkey')
    op.create_foreign_key('usercategory_user_id_fkey', 'usercategory', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'newspapercategory', type_='foreignkey')
    op.create_foreign_key('newspapercategory_newspaper_id_fkey', 'newspapercategory', 'newspaper', ['newspaper_id'], ['id'])
    op.drop_constraint(None, 'alarm', type_='foreignkey')
    op.create_foreign_key('alarm_user_id_fkey', 'alarm', 'user', ['user_id'], ['id'])
    op.alter_column('alarm', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
