"""date

Revision ID: 85b02c8834b5
Revises: 4b244eba70dc
Create Date: 2025-05-09 16:47:32.914130

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85b02c8834b5'
down_revision = '4b244eba70dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newspaper', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('newspaper', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newspaper', sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('newspaper', 'date')
    # ### end Alembic commands ###
