"""Initial migration

Revision ID: abf608e60e7f
Revises: 
Create Date: 2025-05-08 19:14:58.199651

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'abf608e60e7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('AI_ML', 'DATA_SCIENCE', 'CYBERSECURITY', 'CLOUD_COMPUTING', 'DEVOPS', 'BLOCKCHAIN', 'IOT', 'EDGE_COMPUTING', 'VR_AR_METAVERSE', 'QUANTUM_COMPUTING', 'PROGRAMMING_LANGUAGES', 'SOFTWARE_ARCHITECTURE', 'DEVELOPER_TOOLS', 'BIG_DATA', 'OPEN_SOURCE', 'UX_UI', 'MOBILE_WEB_DEVELOPMENT', 'NETWORKING', 'ROBOTICS', 'FINTECH', 'ETC', name='categoryenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newspaper',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('contents', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('createAt', sa.DateTime(), nullable=False),
    sa.Column('updateAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('alarm',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'NONE', name='frequencyenum'), nullable=True),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', name='dayofweekenum'), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('receive_time', sa.DateTime(), nullable=True),
    sa.Column('email_on', sa.Boolean(), nullable=False),
    sa.Column('kakao_on', sa.Boolean(), nullable=False),
    sa.Column('slack_on', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('newspapercategory',
    sa.Column('newspaper_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['newspaper_id'], ['newspaper.id'], ),
    sa.PrimaryKeyConstraint('newspaper_id', 'category_id')
    )
    op.create_table('usercategory',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('selected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usercategory')
    op.drop_table('newspapercategory')
    op.drop_table('alarm')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('newspaper')
    op.drop_table('category')
    # ### end Alembic commands ###
