"""add_save_pref

Revision ID: b26f22ff3db6
Revises: 4ee79eda5c22
Create Date: 2025-05-09 14:27:21.849291

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b26f22ff3db6'
down_revision = '4ee79eda5c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usernewspaperpreference',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('newspaper_id', sa.Integer(), nullable=False),
    sa.Column('preference', sa.Enum('LIKE', 'DISLIKE', 'NONE', name='preferenceenum'), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['newspaper_id'], ['newspaper.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'newspaper_id')
    )
    op.create_table('usernewspapersave',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('newspaper_id', sa.Integer(), nullable=False),
    sa.Column('save_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'newspaper_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usernewspapersave')
    op.drop_table('usernewspaperpreference')
    # ### end Alembic commands ###
