"""passivedelete

Revision ID: b92626cb8663
Revises: 51e3e0e713c1
Create Date: 2025-05-12 11:35:45.308884

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b92626cb8663'
down_revision = '51e3e0e713c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
