"""fix: reproduct tables

Revision ID: c90971cd093d
Revises: 000074b888a8
Create Date: 2025-05-08 17:07:47.458020

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c90971cd093d'
down_revision = '000074b888a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###